### ISSUE TITLE
Feedback for SQLG2C Module 4 through section 4.1

### ISSUE THREAD

**Issue by rgward** [microsoft/sqlworkshops#103]
Feedback through 4.1 from this Module 4 document

https://github.com/microsoft/sqlworkshops/blob/master/SQLGroundToCloud/sqlgroundtocloud/04-SQLServerOnTheMicrosoftAzurePlatform.md

Do you want to put a link to the accompanying slide deck in here?

======================

- General comment "Is Azure SQL" A term?

Personally I think it may not make sense to officially call anything just SQL since that represents a language and not a product

I know we use it ourselves but should we stick to the official service name. I realize Azure SQL is representing both SQL Server in Azure VM and SQL Database

=============

This sentence says

assess your on-premises estate (via Tailspin Toys)

but I don't know what Tailspin Toys is? Perhaps 

"through an example with the Tailspin Toys company"

==========

You organize "Activities" in the beginning of the section but not everything is really an "activity" is it? Also, do you intend for them to click these or just understand the outline of the Module?

==========

4.1 Azure SQL

I would line up the title of this section with the outline at the beginning (make sure to do this for all sections).

As a reader I would like to have some context of what I will be reading about before jumping into the Scenario. Can you add a sentence describing how you plan to teach me Introduction to Azure SQL including using a scenario review, learn deployment options, etc?

=========

They are aware that SQL Server 2008 R2 is approaching end of support

They are aware that SQL Server 2008 R2 has reached end of support

==========

Azure SQL VMs,

I would call it what is says on the website which is SQL Server on Virtual Machines or at least say that is your short name for it

==========

Not sure if too late to change this one up but for the visual I would sync up the terminology. Does Azure SQL Database consist of Managed instances and Databases?

=======

but there are gives and gets to consider

but there are tradeoffs for each option you choose

=======

Azure, quickly.

probably don't need comma

=======

Allscripts

It was not clear if they uses SQL Server on Virtual Machine and MI?

I would bold the option they chose for each example

=======

Because of the large SQL Server surface area, they were able to move about 1.5 terabytes of data smoothly to Azure SQL Managed Instance

I think your are trying to say that MI provides a better experience when you have a large surface area? That could be confusing. I think you mean that they are using a large surface area of features of SQL Server that make MI the best fit?

=======

Feature comparison between SQL database and SQL managed instance

Is this also a comparison with SQL Server?

======

Once you've landed on a deployment option, the next thing to determine is the service tier.

Does service tier options though sometimes dictate my deployment choice?

Also, I got to this point and if I was trying to make my choice I'm not sure I totally understand the benefits of the managed service such as auto HA, performance insights, etc. I think you can glean that from the customer examples but we may want to make this more explicit since this is all about making the choice.

======

Once you've landed on a deployment option, the next thing to determine is the service tier.

SQL Server on Azure Virtual Machines options

There really isn't a "service tier" for SQL VM?

======

For Azure SQL Database, which is the focus of this module, there are several options and tiers available, and the choices will depend on the scenario.

I got down to this point and didn't realize the focus of the module is on Azure SQL Database. I would mention this up front at the beginning of the module

======

For Azure SQL Database, which is the focus of this module, there are several options and tiers available, and the choices will depend on the scenario.

This means this section is more than just service tiers right?

=====

 virtual core (vCore)-based (recommended) 

why is this recommended? What is the default?

=====

Backup storage (RA-GRS).

What is RA-GRS?

=====

Decision 2: Choose service tier for availability

There are performance ramifications from this choice as well right?

=====

Business applications with high I/O requirements.

what is high I/O? I think the docs call it low latency requirements because you can get local SSD performance?

=====

Summary diagram

The In-memory option only being supported for Business Critical is kind of a small point that could be big for some customers. I'm assuming this is In-Memory OLTP? Are there others. We should call that out in the tiering comparison

=====

**Comment by amthomas46** [comment]
Thanks @rgward ! I know this took a ton of effort.  
I think I've addressed everything. Comments are below, and you can review the changes by scrolling to the bottom here: https://github.com/microsoft/sqlworkshops/compare/anna?expand=1  

Thanks, I will review next (4.2) next.

* Added link to slides  
* Removed (via TailspinToys) since it hasn't been introduced yet, added 'through an example with the  Tailspin Toys Gaming division of Wide World Importers'
* Changed "activities in this module are" to "The module is broken up into the following sections:". Also, I am wanting folks to understand the outline of the Module, but also be able to quickly step to a section they may care about more if needed, so I think I'll leave the hyperlinks in?  
* Great catch on the section titles, updated
* For 4.1, added an intro "
	In this section, you'll learn about the different Azure SQL deployment options and service tiers for Tailspin Toys Gaming, a division of Wide World Importers that focuses on online gameplay. You'll start with understanding Tailspin Toys Gaming's scenario deeper, so you can determine which options are best suited to their business needs."  
* Changed to has reached end of support
* Updated to SQL Server in Virtual Machines with shortname
* Added tradeoffs
* Removed comma in Azure, quickly
* Bolded selections for customer examples and specified VM then MI
* For this "Not sure if too late to change this one up but for the visual I would sync up the terminology. Does Azure SQL Database consist of Managed instances and Databases?" this is just reflecting the decisions and guidance with new portal experiences, this slide was agreed and approved on by Asad, Ajay, Alain before Ready, I think it still stands. Feedback noted, but let's leave it for now and see how it's received.
* Changed to "Because Komatsu uses a large surface area of SQL Server features, they chose to move to Azure SQL Managed Instance"
* Changed to "SQL database, SQL managed instance, and SQL Server" feature comparison
* Changed to "Once you have an understanding of the deployment options, it's time to consider some of the details within the service tiers that are available."
* "Also, I got to this point and if I was trying to make my choice I'm not sure I totally understand the benefits of the managed service such as auto HA, performance insights, etc. I think you can glean that from the customer examples but we may want to make this more explicit since this is all about making the choice." To this point, I think that's fair but unfortunately there just isn't time to get into all of it. I will change to platform benefits at the beginning, and hopefully that helps. In the workshop, I plan to briefly discuss each of them
* Added note about Service Tiers for SQL VMs
* Added a note to the beginning "
	Note:
	While all the deployment options will be referenced, the focus of this module is on Azure SQL Managed Instance, with some details that are also related to Azure SQL Database (single database)."
* Changed subsection title to "Azure SQL service tiers and other options"
* Added a little more info about DTUs and why vcores are recommended
* Added full spelling and link to explain RA-GRS
* Changed to Decision 2: Choose service tier for performance and availability
* Good call out about in-memory, added "This is the only tier that can leverage in-memory OLTP to improve performance." with link to Business Critical description
Updated to low latency response requirements instead of high I/O requirements

**Comment by rgward** [comment]
sounds great. Thanks for looking through all the feedback
