### ISSUE TITLE
Feedback for SQLG2C for section 4.4 Module 4

### ISSUE THREAD

**Issue by rgward** [microsoft/sqlworkshops#109]
Here is some feedback for section 4.4 of Module 4

https://github.com/microsoft/sqlworkshops/blob/master/SQLGroundToCloud/sqlgroundtocloud/04-SQLServerOnTheMicrosoftAzurePlatform.md

Module 4 feedback for 4.4

=========

In this series of hands-on labs (throughout Modules 4 and 5)

The hands-on labs in 4 are only here in 4.4 right?

So are the activities in 4.4 required to do activities in Module 5?

=========

Proceed directly to the following Activities from Lab: Database Discovery and Assessment for Migrating to Azure for the hands-on exercises for Tailspin Toys Gaming. 

Am I supposed to go to a different link here or just go through the Activities below?

=========

Throughout the solution, you can use Azure Migrate as the central hub to track the discovery, assessment, and migration of Tailspin Toys.

Will they use the Azure Migrate service in the portal in the labs?

Perhaps "you will use the Azure Migrate service in the Azure portal..." or something like that

=========

Solution Architecture

Do you need to briefly describe what these components will be used for in the solution

SMB Network Share 
Jumpbox
read-only analytics and reports (does this have to go through the Web App?)

=========

Activity 1

Can you scrub out the name of my Azure subscription?

Activity 2

Can I assume in the prereqs we had them open up RDP for the SQL 2008 R2 VM in Azure?

Activity 3

Note:
If you are attending this lab as part of a day-long workshop and were provided an environment to use, you should skip this activity, it was demoed earlier. If you have time at the end of the day, feel free to return to it.

Will they really be able to return to it since I'm assuming Module 5 they will go through other stuff that won't allow them to come back and do this?

==========

Also, why would Tailspin do Activity 3 when they have already decided to go with MI? I understand what you are trying to show but you might mention they they went through Activity 3

==========

11. In the bottom right (see above), select Upload to Azure Migrate. You'll be prompted to sign in (use the credentials you're using for this workshop). Then, select the subscription and Azure Migrate Project created earlier. Select Upload:

You might describe what they are uploading for this step to Azure Migrate and why

==========

The assessment report for a migrating the TailspinToys database to a target platform of Azure SQL Database Managed Instance shows feature parity only with a PowerShell job step. The step listed is associated with a built-in SQL Server Agent Job, and it will not impact the migration of the TailspinToys database to SQL MI.

But does it affect the ability to migrate that job? Why wasn't that called out by the tool in Activity 3?

==========

he database, including the cross-database references and Service broker features, can be migrated as is, providing the opportunity for TailspinToys to have a fully managed PaaS database running in Azure. Previously, their options for migrating a database using features, such as Service Broker, incompatible with Azure SQL Database, were to deploy the database to a virtual machine running in Azure (IaaS) or modify their database and applications to not use the unsupported features. The introduction of Azure SQL MI, however, provides the ability to migrate databases into a managed Azure SQL database service with near 100% compatibility, including the features that prevented them from using Azure SQL Database.

I would add in these links so they can see a complete comparison

https://docs.microsoft.com/en-us/azure/sql-database/sql-database-features
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance-transact-sql-information

==========

Data Migration Assistant Documentation contains more information and best practices around the DMA tool explored in this module.

I think this has the wrong link

==========

You can use this assessment to move the database to Azure SQL Database or an Azure SQL Managed Instance

Should this just say Azure SQL Managed Instance?

I went to the next steps link at

https://github.com/microsoft/sqlworkshops/blob/master/AzureSQLLabs/Lab-MigratingToAzureSQLManagedInstance.md

and I wasn't sure how it links back? 

It says

In this lab you'll use the results of an assessment to migrate a database to a Azure SQL Database Managed Instance.

but it doesn't say what I needed to do to see the results of the assessment?

**Comment by amthomas46** [comment]
* Right now, as it stands, you have to do Module 4 to do Module 5. For the workshop, Module 4 is done by me and Spektra. But a future enhancement could be to fully isolate them
* Added link to lab, you're right, no need to go through each link  
* Updated to you use will Azure Migrate. Currently we actually just use Azure Migrate for discovery and assessment but not actually migrating, but as the feature becomes better I'll add it to do that (FYI only)
* scrubbed Azure subscription
* On this "Will they really be able to return to it since I'm assuming Module 5 they will go through other stuff that won't allow them to come back and do this?" if I am understanding correctly, yes, they will still be able to come back and do this if they have time, the labs in module 5 won't affect that. It doesn't make a ton of sense to assess after migrating, but for learning purposes and lab purposes, they could totally do it
* Added a note about why still assessing Azure SQL DB and MI if MI was already chosen
* Added note about uploading to Azure Migrate
* Added comparison references
* fixed DMA docs links
* Added link backs to module 4 and 5 at the end of the two labs
* Added note about powershell job step
* Added more info about SMB and two references in the lab
* added info about the leaderboard statistics report  


Updates added, thank you! I will conduct a quick review to make sure I haven't introduced new typos or spelling errors. Thanks again.
