### ISSUE TITLE
Lab-DatabaseDiscoveryAndAssessmentForMigratingToAzure.md

### ISSUE THREAD

**Issue by jeroenterheerdt** [microsoft/sqlworkshops#149]
Activity 4, Step 11 assumes that next to the SQL DB assessment the SQL MI assessment was also uploaded to Azure Migrate, but that instruction is missing from the notebook. Just copy paste it from step 11 and 12 in Activity 3.

**Comment by jeroenterheerdt** [comment]
@amthomas46

**Comment by amthomas46** [comment]
In activity 4, Step 9, it says "Review the assessment of ability to migrate to Azure SQL Database Managed Instance, then upload to Azure Migrate, as in the previous activity:"  

I feel like it's easy to do once you click "Upload to Azure Migrate" and you've done it just before in the previous activity. Do you think otherwise? I know you're doing it playing someone who doesn't know anything, so let me know what you think we should do here.

**Comment by jeroenterheerdt** [comment]
Oh - I totally missed that note. Maybe we should just make it more discoverable ;)
